export const FETCH_FORECAST_LIST_START = "FETCH_FORECAST_LIST_START";
export const FETCH_FORECAST_LIST_FULFILLED = "FETCH_FORECAST_LIST_FULFILLED";
export const UPDATE_CURRENT_FORECAST_START = "UPDATE_CURRENT_FORECAST_START";
export const UPDATE_CURRENT_FORECAST_FULFILLED =
  "UPDATE_CURRENT_FORECAST_FULFILLED";
